### ISSUE TITLE
Generate Docker image

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [thecoshman/http#118]
Is it possible to provide the Docker image on hub.docker ?

**Comment by nabijaczleweli** [comment]
I've made https://hub.docker.com/repository/docker/nabijaczleweli/http; can you check if that works for you?

**Comment by thecoshman** [comment]
Wow, I'm surprised a Docker image is wanted here... kinda the point of this is that it's light weight enough. I wouldn't really consider something that this repo should concern itself with to be fair. If nab want's to support it, as they seem to be willing to do, then I'll let them have their fun.

**Comment by nabijaczleweli** [comment]
@MarcAntoine-Arnaud Pirate's blabbering notwithstanding, does the Docker repository I posted work for you?

**Comment by nabijaczleweli** [comment]
@MarcAntoine-Arnaud ping

**Comment by nabijaczleweli** [comment]
@MarcAntoine-Arnaud two-year bump

**Comment by CodeSandwich** [comment]
This Docker image looks very good and I would be happy to use it if you bumped the http version inside. For now I'm sticking with https://hub.docker.com/r/p1st/httplz which is probably already abandoned, but it's still fresh enough for my use-case of a local yet portable dev utility. It would be great to link your Docker image somewhere in this repo because the `http` name is probably the least searchable keyword on Docker Hub.

(As a sidenote, IMO the name is probably hurting this project, it looks like a low-level generic library and not a ready to go executable. I was able to find the Docker image I'm currently used only because I searched for the unofficial name that Arch maintainers came up with: httplz. I love this name, it's short, clever and original while carrying over the legacy of this project's name, I wish that it was official.)

**Comment by nabijaczleweli** [comment]
I pushed 2.1.0; if I remember I'll keep uploading new releases as they happen.

httplz is one of the binary names. I'll grant you, the nomenclature situation is Not Great, but I can't really fix it.

**Comment by wrenix** [comment]
Sadly none of the images is updated to the latest release.
For my a container image is nice for orchestration of software, so i will like to have an container image with just the binary in there (a SCRATCH Container).

In first step i will try [dufs](https://github.com/sigoden/dufs).

**Comment by thecoshman** [comment]
I still don't fully get the desire for this tool to be offered in a container, but I'll look in to. 
One thing that's going to add to the fun is that GitHub will be charging for things... 
I need to think about long term solutions, and very much open to suggestions.
