### ISSUE TITLE
Support Range request header (Ability to stream videos from random positions)

### ISSUE THREAD

**Issue by NawfelBgh** [thecoshman/http#36]
# Feature request: Ability to stream videos from random positions in the middle.

## Expected behaviour

* Share a directory containing a big(ish) video file;
* Connect to the server with a browser (It should better be from a computer different than the one hosting the server to add some network latency);
* Click the video name; The browser will start loading and displaying the video;
* You will notice in the video progress-bar that the browser shows how much it has pre-fetched (downloaded);
* Jump (by clicking/tapping in the progress-bar) to a position in the video that is not loaded yet;
* **The browser should start displaying the video from that position**.

## Observed behaviour

Jumping to the middle doesn't work with and without the -e flag. I tested it in my mobile's Firefox with a >2h video. It can't jump to positions that are not loaded:

* I **can** jump to positions in the video that was already loaded or pre-fetched by firefox. This is always the case with small files and when I use Firefox from the same laptop as the server since the file is \~instantly downloaded.
* What I can't do is jump to a position which is not yet loaded. For example, when I open a 2hours long video, it starts from 0h00. if I try to jump to **1h00**, it will fail to do so and it will jump instead to **1min xy seconds** (or wherever the download is so far).

-------------------

From inspecting what http headers are sent when firefox tries to jump to a not-loaded position in [this youtube video](https://r5---sn-hgn7zn7s.googlevideo.com/videoplayback?key=cms1&gir=yes&mime=video%2Fmp4&requiressl=yes&ratebypass=yes&dur=346.046&lmt=1484123052879736&source=youtube&clen=15053869&id=o-ANabftMGPfGu6vXOHu9TF_px2mY-v7HUAwzfaC8UZLYb&expire=1484193348&ei=46l2WM2VOsfycuTGo9AN&pl=17&ipbits=0&ip=41.109.236.221&sparams=clen,dur,ei,expire,gir,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn&signature=5C096A27A1D5D53A18742D85F324ECF71C482C2E.6D9B3D096D2DF27DDB8B2B677050721D92743F76&itag=18&upn=OURRDchDiSI&cmbypass=yes&redirect_counter=1&req_id=b284bf5a3f79a3ee&cms_redirect=yes&mm=30&mn=sn-hgn7zn7s&ms=nxu&mt=1484171710&mv=m&nh=IgpwcjAyLm1yczAyKg8yMTMuMTQ0LjE3Ni4yMjA) (the link should die soon), firefox sends few video-specific http-options, and the server responds respectively:

    1st Request
    ===========
    
    Host: r5---sn-hgn7zn7s.googlevideo.com
    User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
    Accept: video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5
    Accept-Language: en-US,en;q=0.5
    Range: bytes=7798784-
    Referer: https://r5---sn-hgn7zn7s.googlevideo.com/videoplayback?key=cms1&gir=yes&mime=video%2Fmp4&requiressl=yes&ratebypass=yes&dur=346.046&lmt=1484123052879736&source=youtube&clen=15053869&id=o-ANabftMGPfGu6vXOHu9TF_px2mY-v7HUAwzfaC8UZLYb&expire=1484193348&ei=46l2WM2VOsfycuTGo9AN&pl=17&ipbits=0&ip=41.109.236.221&sparams=clen,dur,ei,expire,gir,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn&signature=5C096A27A1D5D53A18742D85F324ECF71C482C2E.6D9B3D096D2DF27DDB8B2B677050721D92743F76&itag=18&upn=OURRDchDiSI&cmbypass=yes&redirect_counter=1&req_id=b284bf5a3f79a3ee&cms_redirect=yes&mm=30&mn=sn-hgn7zn7s&ms=nxu&mt=1484171710&mv=m&nh=IgpwcjAyLm1yczAyKg8yMTMuMTQ0LjE3Ni4yMjA
    DNT: 1
    Connection: keep-alive
    
    
    1st response
    ============
    
    Accept-Ranges: bytes
    Alt-Svc: quic=":443"; ma=2592000
    Cache-Control: private, max-age=21234
    Connection: close
    Content-Length: 7255085
    Content-Range: bytes 7798784-15053868/15053869
    Content-Type: video/mp4
    Date: Wed, 11 Jan 2017 21:56:54 GMT
    Expires: Wed, 11 Jan 2017 21:56:54 GMT
    Last-Modified: Wed, 11 Jan 2017 08:24:12 GMT
    Server: gvs 1.0
    X-Content-Type-Options: nosniff
    
    Middle request
    ==============

    Host: r5---sn-hgn7zn7s.googlevideo.com
    User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
    Accept: video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5
    Accept-Language: en-US,en;q=0.5
    Range: bytes=11075584-
    Referer: https://r5---sn-hgn7zn7s.googlevideo.com/videoplayback?key=cms1&gir=yes&mime=video%2Fmp4&requiressl=yes&ratebypass=yes&dur=346.046&lmt=1484123052879736&source=youtube&clen=15053869&id=o-ANabftMGPfGu6vXOHu9TF_px2mY-v7HUAwzfaC8UZLYb&expire=1484193348&ei=46l2WM2VOsfycuTGo9AN&pl=17&ipbits=0&ip=41.109.236.221&sparams=clen,dur,ei,expire,gir,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn&signature=5C096A27A1D5D53A18742D85F324ECF71C482C2E.6D9B3D096D2DF27DDB8B2B677050721D92743F76&itag=18&upn=OURRDchDiSI&cmbypass=yes&redirect_counter=1&req_id=b284bf5a3f79a3ee&cms_redirect=yes&mm=30&mn=sn-hgn7zn7s&ms=nxu&mt=1484171710&mv=m&nh=IgpwcjAyLm1yczAyKg8yMTMuMTQ0LjE3Ni4yMjA
    DNT: 1
    Connection: keep-alive
    
    
    Response
    ========
    Accept-Ranges: bytes
    Alt-Svc: quic=":443"; ma=2592000
    Cache-Control: private, max-age=21214
    Connection: close
    Content-Length: 3978285
    Content-Range: bytes 11075584-15053868/15053869
    Content-Type: video/mp4
    Date: Wed, 11 Jan 2017 21:57:14 GMT
    Expires: Wed, 11 Jan 2017 21:57:14 GMT
    Last-Modified: Wed, 11 Jan 2017 08:24:12 GMT
    Server: gvs 1.0
    X-Content-Type-Options: nosniff

**Comment by nabijaczleweli** [comment]
IOW this is "Support `Range` request header"

**Comment by nabijaczleweli** [comment]
@NawfelBgh Check the `feature/36-range-header` branch. I've done both artificial (`curl --range`) and real-world (opened a video in Firefox) tests, both successful, so if you'd be so kind as to try it yourself...

**Comment by NawfelBgh** [comment]
Sorry for the late response. I'll check it.

**Comment by NawfelBgh** [comment]
Sorry for the late response. I'll check it.

**Comment by NawfelBgh** [comment]
Thanks again for the great work. I tested the feature and I find it a little buggy.

### My experiment
* I launch the server in my laptop.
* I browse it using firefox v50 for android (kitkat) in my phone which is connected to the laptop through wifi.
* I click the name of a video file of `2 hours`.
  * The video starts from `00:00:00` **as expected**
* I click on the middle of the progress bar.
  * Firefox starts showing the video from (around) `01:00:00` **as expected**
  * **Though there is a catch**:
    * When firefox switched to playing from `01:00:00`, it started displaying it in the progress bar as if it was the last second of the video. which means that I can no longer jump to positions post where the video is currently playing.
    * And when I tap in the video-progress-bar on a position before the current one. Say `00:30:00` for example, Firefox looks like it's trying to load it, but then it starts playing from some position in the very beginning of the video (for example `00:00:50`).
    * After that Firefox fails at every subsequent attempt to jump into a later position.

I witnessed this same behaviour in many repetitions of the same experiment.

**Comment by nabijaczleweli** [comment]
I think I'm at the edge of my and the frameworks' capacity to do this, but I just fixed a bug, so if you could re-check...

**Comment by NawfelBgh** [comment]
I pulled the commit ba09fc3b97555a25fc1b00091d2ddf7677342aa9 and did a clean build.
The problem persists. Jumping to a new position works only the first time but all the previously mentioned problems persist

Here is the log:

```
Hosting "." on port 8000...
Ctrl-C to stop.

[2017-01-22 18:09:57] 192.168.1.34:38114 was served directory listing for /mydata/Downloads/RL
[2017-01-22 18:09:57]                    encoded as gzip for 569.1% ratio
[2017-01-22 18:10:08] 192.168.1.34:38116 was served file /mydata/Downloads/RL/Tutorial_Introduction_to_Reinforcement_Learning_with_Function_Approximation_medium.mp4 as video/mp4
[2017-01-22 18:10:27] 192.168.1.34:38117 was served file /mydata/Downloads/RL/Tutorial_Introduction_to_Reinforcement_Learning_with_Function_Approximation_medium.mp4 from byte 434044928 as video/mp4
[2017-01-22 18:10:32] 192.168.1.34:38118 was served file /mydata/Downloads/RL/Tutorial_Introduction_to_Reinforcement_Learning_with_Function_Approximation_medium.mp4 from byte 0 as video/mp4

```

* In `[2017-01-22 18:09:57]`, the directory was delivered
* In `[2017-01-22 18:10:08]`, the file was delivered and Firefox started loading the video from 00:00:00
* `[2017-01-22 18:10:27]` is the result of me clicking in the progress bar to jump to a new position. This jump is successful but as I said previously, this new position becomes the last part of the progress bar. So there is no room to click to go forward. This problem happens from the browser in the same laptop as the server too.
* [2017-01-22 18:10:32] is the result of me clicking in a position between the start of the video and the current one. I'm curious why the log says `from byte 0`
* I tried to jump to other positions afterwards but that failed. It looks like firefox didn't bother sending any request.

**Comment by nabijaczleweli** [comment]
> I'm curious why the log says `from byte 0`

Because we receive header `Range` as `Some(Bytes([AllFrom(0)]))` because the headers *sent* by FF contain 
![FF SS](https://cloud.githubusercontent.com/assets/6709544/22186270/5f97b92e-e0f3-11e6-8afa-926ed2448c89.png).

> It looks like firefox didn't bother sending any request.

Now that I look at my request log it certainly does seem the case, which is weird, because it *should*.

**Comment by NawfelBgh** [comment]
For record, I'll past the request and response headers corresponding to each situation. And I will try to reach for help in Mozilla irc.

>The code handling range headers is here https://github.com/thecoshman/http/compare/feature/36-range-header#diff-bcc2b8e33d1d11d5142549cfc9d67006R115

* This corresponds to the first time the video is visited... Firefox starts playing it at 00:00:00:

```
Request headers 1


Host: 192.168.1.33:8000
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://192.168.1.33:8000/Downloads/DL/deep%20learning%20for%20visual%20recognition
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Pragma: no-cache
Cache-Control: no-cache


Response headers 1

Accept-Ranges: bytes
Content-Length: 820801371
Content-Type: video/mp4
Date: Sun, 22 Jan 2017 22:49:27 GMT
Last-Modified: Fri, 12 Aug 2016 01:16:58 GMT
Server: http/1.0.0
```

* This corresponds to when I jumped to a random position in the video... Firefox starts playing from there:

```
Request headers 2

Host: 192.168.1.33:8000
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5
Accept-Language: en-US,en;q=0.5
Range: bytes=755073024-
Referer: http://192.168.1.33:8000/Downloads/DL/deep%20learning%20for%20visual%20recognition/CS231n_Winter_2016_Lecture_9_Visualization_Deep_Dream_Neural_Style_Adversarial_Examples_hd720.mp4
DNT: 1
Connection: keep-alive


Response header 2

Accept-Ranges: bytes
Content-Length: 65728347
Content-Type: video/mp4
Date: Sun, 22 Jan 2017 22:49:31 GMT
Last-Modified: Fri, 12 Aug 2016 01:16:58 GMT
Range: bytes=755073024-820801371
Server: http/1.0.0
```

* This corresponds to when I jump to a position past the privious one (but not 0:00:00)... Firefox does something really weird. Why does it send `Range: bytes=0-`?

```
Request headers 3

Host: 192.168.1.33:8000
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5
Accept-Language: en-US,en;q=0.5
Range: bytes=0-
Referer: http://192.168.1.33:8000/Downloads/DL/deep%20learning%20for%20visual%20recognition/CS231n_Winter_2016_Lecture_9_Visualization_Deep_Dream_Neural_Style_Adversarial_Examples_hd720.mp4
DNT: 1
Connection: keep-alive


Response headers 3

Accept-Ranges: bytes
Content-Length: 820801371
Content-Type: video/mp4
Date: Sun, 22 Jan 2017 22:49:32 GMT
Last-Modified: Fri, 12 Aug 2016 01:16:58 GMT
Range: bytes=0-820801371
Server: http/1.0.0
```

**Comment by nabijaczleweli** [comment]
> try to reach for help in Mozilla irc

Sounds like a good idea, I do hope you get a satisfactory answer.

> Firefox does something really weird. Why does it send Range: bytes=0-?

I haven't a foggiest.

**Comment by NawfelBgh** [comment]
Here are the requests/responses from interaction with a [Youtube video](https://r2---sn-5abxgpxuxaxjvh-5abs.googlevideo.com/videoplayback?ipbits=0&mime=video%2Fmp4&initcwndbps=175000&itag=22&ratebypass=yes&requiressl=yes&mt=1485129642&signature=C51B593505463574444A18C2232FB702C75C33A4.828BB7E35FA9FC794F6DB2A3C042B5FAB0AEA78B&id=o-AC6pAKbrNe--YJk545QQMRd47KUJ1Smmnfx48CdjQ2Q1&mm=31&mn=sn-5abxgpxuxaxjvh-5abs&dur=450.049&pl=17&ip=41.109.131.131&lmt=1479119987205010&ei=X0iFWOXvFsu61gKc0ZOwBg&ms=au&source=youtube&mv=m&expire=1485151423&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=atbbLmOIxc8&key=yt6&cmbypass=yes) (the link will die in few hours) which works just fine.

* When I load the video

```
Request

Host: r2---sn-5abxgpxuxaxjvh-5abs.googlevideo.com
User-Agent: Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Range: bytes=1058980-
If-Range: Mon, 14 Nov 2016 10:39:47 GMT


Response

Accept-Ranges: bytes
Alt-Svc: quic=":443"; ma=2592000
Cache-Control: private, max-age=21178
Connection: close
Content-Length: 30842847
Content-Range: bytes 1058980-31901826/31901827
Content-Type: video/mp4
Date: Mon, 23 Jan 2017 00:05:45 GMT
Expires: Mon, 23 Jan 2017 00:05:45 GMT
Last-Modified: Mon, 14 Nov 2016 10:39:47 GMT
Server: gvs 1.0
X-Content-Type-Options: nosniff

```

* When I jump to 3:35

```
Request

Host: r2---sn-5abxgpxuxaxjvh-5abs.googlevideo.com
User-Agent: Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0
Accept: video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5
Accept-Language: en-US,en;q=0.5
Range: bytes=17891328-
Referer: https://r2---sn-5abxgpxuxaxjvh-5abs.googlevideo.com/videoplayback?ipbits=0&mime=video%2Fmp4&initcwndbps=175000&itag=22&ratebypass=yes&requiressl=yes&mt=1485129642&signature=C51B593505463574444A18C2232FB702C75C33A4.828BB7E35FA9FC794F6DB2A3C042B5FAB0AEA78B&id=o-AC6pAKbrNe--YJk545QQMRd47KUJ1Smmnfx48CdjQ2Q1&mm=31&mn=sn-5abxgpxuxaxjvh-5abs&dur=450.049&pl=17&ip=41.109.131.131&lmt=1479119987205010&ei=X0iFWOXvFsu61gKc0ZOwBg&ms=au&source=youtube&mv=m&expire=1485151423&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=atbbLmOIxc8&key=yt6&cmbypass=yes
DNT: 1
Connection: keep-alive

Response

Accept-Ranges: bytes
Alt-Svc: quic=":443"; ma=2592000
Cache-Control: private, max-age=21170
Connection: close
Content-Length: 14010499
Content-Range: bytes 17891328-31901826/31901827
Content-Type: video/mp4
Date: Mon, 23 Jan 2017 00:05:53 GMT
Expires: Mon, 23 Jan 2017 00:05:53 GMT
Last-Modified: Mon, 14 Nov 2016 10:39:47 GMT
Server: gvs 1.0
X-Content-Type-Options: nosniff
```

* When I jump back to 1:53

```
Request

Host: r2---sn-5abxgpxuxaxjvh-5abs.googlevideo.com
User-Agent: Mozilla/5.0 (Android 4.4; Mobile; rv:41.0) Gecko/41.0 Firefox/41.0
Accept: video/webm,video/ogg,video/*;q=0.9,application/ogg;q=0.7,audio/*;q=0.6,*/*;q=0.5
Accept-Language: en-US,en;q=0.5
Range: bytes=10059776-
Referer: https://r2---sn-5abxgpxuxaxjvh-5abs.googlevideo.com/videoplayback?ipbits=0&mime=video%2Fmp4&initcwndbps=175000&itag=22&ratebypass=yes&requiressl=yes&mt=1485129642&signature=C51B593505463574444A18C2232FB702C75C33A4.828BB7E35FA9FC794F6DB2A3C042B5FAB0AEA78B&id=o-AC6pAKbrNe--YJk545QQMRd47KUJ1Smmnfx48CdjQ2Q1&mm=31&mn=sn-5abxgpxuxaxjvh-5abs&dur=450.049&pl=17&ip=41.109.131.131&lmt=1479119987205010&ei=X0iFWOXvFsu61gKc0ZOwBg&ms=au&source=youtube&mv=m&expire=1485151423&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=atbbLmOIxc8&key=yt6&cmbypass=yes
DNT: 1
Connection: keep-alive

Response

Accept-Ranges: bytes
Alt-Svc: quic=":443"; ma=2592000
Cache-Control: private, max-age=21166
Connection: close
Content-Length: 21842051
Content-Range: bytes 10059776-31901826/31901827
Content-Type: video/mp4
Date: Mon, 23 Jan 2017 00:05:57 GMT
Expires: Mon, 23 Jan 2017 00:05:57 GMT
Last-Modified: Mon, 14 Nov 2016 10:39:47 GMT
Server: gvs 1.0
X-Content-Type-Options: nosniff
```

**Comment by nabijaczleweli** [comment]
Alright, that leaves us to a question: what do *we* do differently from YT that matters? I tried a couple headers but to no avail.

**Comment by NawfelBgh** [comment]
I found the fix:

* The server should respond with `Content-Range` not `Range`.
* the `to` in `(from, to)` should be the `flen - 1`. In the youtube's example I verified that `to - from == clen - 1`.

Try applying this diff:

```diff
diff --git a/src/ops.rs b/src/ops.rs
index 60860d7..def2773 100644
--- a/src/ops.rs
+++ b/src/ops.rs
@@ -209,13 +209,14 @@ impl HttpHandler {
 
         let mut buf = vec![0; (to + 1 - from) as usize];
         let mut f = File::open(&req_p).unwrap();
+        let flen = f.metadata().unwrap().len();
         f.seek(SeekFrom::Start(from)).unwrap();
         f.read(&mut buf).unwrap();
 
         Ok(Response::with((status::PartialContent,
                            (Header(headers::Server(USER_AGENT.to_string())),
                             Header(headers::LastModified(headers::HttpDate(file_time_modified(&req_p)))),
-                            Header(headers::Range::bytes(from, to + 1)),
+                            Header(headers::ContentRange(headers::ContentRangeSpec::Bytes { range: Some((from, to)), instance_length: Some(flen) })),
                             Header(headers::AcceptRanges(vec![headers::RangeUnit::Bytes]))),
                            buf,
                            mime_type)))
@@ -274,7 +275,7 @@ impl HttpHandler {
                            f,
                            (Header(headers::Server(USER_AGENT.to_string())),
                             Header(headers::LastModified(headers::HttpDate(file_time_modified(&req_p)))),
-                            Header(headers::Range::bytes(b_from, flen)),
+                            Header(headers::ContentRange(headers::ContentRangeSpec::Bytes { range: Some((b_from, flen - 1)), instance_length: Some(flen) })),
                             Header(headers::ContentLength(clen)),
                             Header(headers::AcceptRanges(vec![headers::RangeUnit::Bytes]))),
                            mt)))

```

**Comment by nabijaczleweli** [comment]
> The server should respond with Content-Range not Range.

I just got to this myself xD A bloody moron, I am.

> the to in (from, to) should be

This is really prone to off-by-1s, isn't it?

**Comment by NawfelBgh** [comment]
> This is really prone to off-by-1s, isn't it?

Yes. So true.

I'm lazy to send a pull request. Please apply the fix and thank you for doing all the work =)

**Comment by nabijaczleweli** [comment]
Yeah, I'm on it

**Comment by nabijaczleweli** [comment]
This works now, incredible! Please check the branch again.

**Comment by NawfelBgh** [comment]
Everything works as expected. I tested 49db4888f951567efe575915 from both firefox for Android and from the same laptop and no errors occurred.

**Comment by nabijaczleweli** [comment]
Magnificent. This will land in the next released version, then (1.1.0, probably).
